"""Embed price-loading code into the standalone executable, without price data."""
from __future__ import annotations

import argparse
import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

SCRIPT = ROOT / "oai-usage"
SOURCE = ROOT / "oai_price_catalog.py"
BEGIN = "# BEGIN GENERATED PRICE CATALOG\n"
END = "# END GENERATED PRICE CATALOG\n"


def bundled_script(script: Path = SCRIPT) -> str:
    text = script.read_text(encoding="utf-8")
    if text.count(BEGIN) != 1 or text.count(END) != 1:
        raise ValueError("Standalone price section is missing or ambiguous")
    prefix, rest = text.split(BEGIN)
    _, suffix = rest.split(END)
    source = SOURCE.read_text(encoding="utf-8")
    tree = ast.parse(source)
    # Skip the module docstring, future import, and standalone worker invocation.
    start = tree.body[2].lineno - 1
    stop = tree.body[-1].lineno - 1
    lines = source.splitlines(keepends=True)
    code = "".join(lines[start:stop]).rstrip() + "\n"
    # A streamed script has no file to reopen. Embed the same bounded downloader
    # as fixed child-process source, generated from its canonical implementation.
    download = next(node for node in tree.body if isinstance(node, ast.FunctionDef) and node.name == "_download")
    entry = next(node for node in tree.body if isinstance(node, ast.FunctionDef) and node.name == "download_main")
    worker = "".join(lines[start:download.end_lineno]) + "\n\n" + "".join(lines[entry.lineno - 1:entry.end_lineno]) + "\n\ndownload_main()\n"
    compile(worker, "<oai-usage-download-worker>", "exec")
    placeholder = "STDIN_DOWNLOAD_WORKER = None\n"
    if code.count(placeholder) != 1:
        raise ValueError("Standalone download worker placeholder is missing or ambiguous")
    literal = "STDIN_DOWNLOAD_WORKER = (\n" + "".join(f"    {line!r}\n" for line in worker.splitlines(keepends=True)) + ")\n"
    code = code.replace(placeholder, literal)
    result = prefix + BEGIN + "# Generated by scripts/bundle_prices.py; edit oai_price_catalog.py.\n" + code + END + suffix
    compile(result, str(script), "exec")
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the executable needs rebuilding")
    args = parser.parse_args()
    text = bundled_script()
    if args.check:
        if SCRIPT.read_text(encoding="utf-8") != text:
            parser.exit(1, "Run python3 scripts/bundle_prices.py to refresh oai-usage\n")
    else:
        # Write in place to preserve executable permissions.
        SCRIPT.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
