"""Embed price-loading code into the standalone executable, without price data."""
from __future__ import annotations

import argparse
import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

SCRIPT = ROOT / "oai-usage"
SOURCE = ROOT / "oai_price_catalog.py"
BEGIN = "# BEGIN GENERATED PRICE CATALOG\n"
END = "# END GENERATED PRICE CATALOG\n"


def bundled_script(script: Path = SCRIPT) -> str:
    text = script.read_text(encoding="utf-8")
    if text.count(BEGIN) != 1 or text.count(END) != 1:
        raise ValueError("Standalone price section is missing or ambiguous")
    prefix, rest = text.split(BEGIN)
    _, suffix = rest.split(END)
    source = SOURCE.read_text(encoding="utf-8")
    tree = ast.parse(source)
    # Skip the module docstring, future import, and standalone worker invocation.
    start = tree.body[2].lineno - 1
    stop = tree.body[-1].lineno - 1
    code = "".join(source.splitlines(keepends=True)[start:stop]).rstrip() + "\n"
    result = prefix + BEGIN + "# Generated by scripts/bundle_prices.py; edit oai_price_catalog.py.\n" + code + END + suffix
    compile(result, str(script), "exec")
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the executable needs rebuilding")
    args = parser.parse_args()
    text = bundled_script()
    if args.check:
        if SCRIPT.read_text(encoding="utf-8") != text:
            parser.exit(1, "Run python3 scripts/bundle_prices.py to refresh oai-usage\n")
    else:
        # Write in place to preserve executable permissions.
        SCRIPT.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
